Elastio with PHP Lumen API
elastio/contrib pull request #11
Opened 2022-03-29 10:59 UTC by rsaylor73

2022-03-29 13:00 UTC, anelson requested changes
This is a great example of how Elastio can be integrated into another application.

PHP isn't a language I have any experience with so I don't feel qualified to review the PHP code; we'll accept that as-is.  However I've made a few comments about the interaction with `elastio`.  I placed them on the EC2 backup code but they apply to all of the `elastio` invocations.

2022-03-29 13:28 UTC, rsaylor73 commented on elastio-api-php-lumen/app/Service/EapService.php
> +        $cmd = "cd /home/ubuntu && sudo elastio ec2 backup --instance-id {$instanceID} 2>&1; echo $?";
yes the API is running as a web user "www-data" if on Ubuntu so we need to be in the visuders file that is documented. 

Another option would be to queue the job then run from cron but with this simple integration that was not the direction.

The path does not exist when running from a php shell. From past experience this is the way.

2022-04-02 12:33 UTC, rsaylor73 commented on elastio-api-php-lumen/app/Service/EapService.php
> +        $cmd = "cd /home/ubuntu && sudo elastio ec2 backup --instance-id {$instanceID} 2>&1; echo $?";
Added sanitation on all inputs from the user.

2022-04-03 19:04 UTC, anelson approved these changes
:+1:

2022-04-04 10:45 UTC, merged