add dynamodb example upon Naj's request
elastio/contrib pull request #13
Opened 2022-04-05 13:50 UTC by mvovchuk

2022-04-05 15:19 UTC, anelson requested changes

2022-04-06 07:44 UTC, mvovchuk commented on dynamo-db-protect-and-restore-example/dynamoDBinstructions.md
> +# Backup DynamoDB Tables using Elastio
done

2022-04-06 13:46 UTC, mvovchuk commented on dynamo-db-protect-and-restore-example/DynamoElastio.py
> +#!/usr/bin/env python
@anelson https://github.com/bchew/dynamodump/blob/master/dynamodump/dynamodump.py this is the original, I am not sure how to include it - the original Licence is https://github.com/bchew/dynamodump/blob/master/LICENSE

2022-04-06 15:33 UTC, mvovchuk commented on dynamo-db-protect-and-restore-example/DynamoElastio.py
> +#!/usr/bin/env python
done

2022-04-06 16:55 UTC, anelson approved these changes
Please make requested changes prior to merge

2022-04-06 16:55 UTC, anelson commented on dynamo-db-protect-and-restore-example/README.md
> +## LICENCE
```suggestion
## LICENSE
```

2022-04-06 16:55 UTC, anelson commented on dynamo-db-protect-and-restore-example/README.md
> +Elastio-specific modifications are Copyright 2022 Elastio Software, Inc, and are hereby released under the MIT License as was the original work upon which this version is derived (https://github.com/
Let's make that hyperlink a bit prettier:

```suggestion
Elastio-specific modifications are Copyright 2022 Elastio Software, Inc, and are hereby released under the MIT License as was the [original work by bchew](https://github.com/bchew/dynamodump) from which this version is derived.
```

2022-04-07 07:02 UTC, merged