added docker image for ECS, added docs
elastio/contrib pull request #26
Opened 2022-06-03 13:15 UTC by ViacheslavSaievskyi

Docker file to building docker image was added as an example of how it could work with AWS ECS
Entered minimal documentation

2022-06-06 20:52 UTC, swarmer commented on elastio-stream-kafka/README.md
> +1. Create an EC2 instance (Amazon Linux 2 AMI (HVM) - Kernel 5.10, SSD Volume Type, instance type: t2.xlagre) in the same VPC as your MSK cluster.
```suggestion
1. Create an EC2 instance (Amazon Linux 2 AMI (HVM) - Kernel 5.10, SSD Volume Type, instance type: t2.xlarge) in the same VPC as your MSK cluster.
```

2022-06-06 20:52 UTC, swarmer commented on elastio-stream-kafka/README.md
> +    10. Press `Create` button. This will run the task according to the selected schedule.
Will this push logs anywhere? I feel like this needs a follow-up section describing how to see the logs for troubleshooting.

2022-06-21 14:43 UTC, ivankovnatsky commented on elastio-stream-kafka/Dockerfile
> +CMD python3 docker_backup_app.py
```suggestion
ENTRYPOINT ["python3"]
CMD ["docker_backup_app.py"]
```

2022-06-29 09:38 UTC, ivankovnatsky requested changes

2022-06-29 09:38 UTC, ivankovnatsky commented on elastio-stream-kafka/Dockerfile
> +RUN apt-get update && apt-get upgrade -y
```suggestion
RUN apt-get update && apt-get upgrade -y --no-install-recommends --no-install-suggests
```

2022-06-29 09:38 UTC, ivankovnatsky commented on elastio-stream-kafka/Dockerfile
> +RUN apt-get update && apt-get upgrade -y
I would not upgrade, rather just taking a needed base image with newest relevant tag.

2022-06-29 09:38 UTC, ivankovnatsky commented on elastio-stream-kafka/Dockerfile
> +RUN apt-get install -y python3-pip python3
Why not put apt-get install as a single RUN?

2022-07-05 13:25 UTC, ivankovnatsky commented on elastio-stream-kafka/Dockerfile
> +FROM public.ecr.aws/elastio-dev/elastio-cli:0.17.0-master
Per Adam let's use `:latest` here.

2024-04-17 14:18 UTC, closed without merging