Elastio fargate stream scheduled backup
elastio/contrib pull request #9
Opened 2022-01-31 18:45 UTC by ViacheslavSaievskyi

2022-03-25 15:49 UTC, anelson requested changes

2022-04-26 19:24 UTC, anelson commented
@ViacheslavSaievskyi what's the status of this PR?  Since I requested changes nothing more seems to have been done.

2022-04-27 16:48 UTC, ViacheslavSaievskyi commented
> @ViacheslavSaievskyi what's the status of this PR? Since I requested changes nothing more seems to have been done.

2022-04-27 17:55 UTC, anelson requested changes
I made three comments earlier; none of them have been addressed.  Address them and re-request.

Second, all of this content should be in a single sub-folder in `contrib`.  Right now you're adding a bunch of folders to the root which will be confusing and misleading.

Move everything to a folder called `fargate-stream-backup`.

Finally, why are there `mp4` files in this repo?  You should never put large binary files in Git.  We have Git LFS for this purpose if you need them as part of the content.

2022-04-28 11:25 UTC, anelson approved these changes
Approved, but make sure to move your `.gitignore` as instructed, before you merge.

Also when you merge, edit the commit message so it's meaningful.  Right now it will default to a mess of short commit messages reflecting all of the changes you made up to this point.  We don't want that, we want it squashed into a clean description of this change.

2022-04-28 11:25 UTC, anelson commented on .gitignore
> -*.vsix
Don't put this here.  You can have your own `.gitignore` inside of the `elastio-fargate-stream-backup` directory where project-specific ignores go.

2022-04-29 10:31 UTC, merged